spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/wealth_pulse
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
goldapi.key=${GOLD_API_KEY}
alphavantage.key=${ALPHA_VANTAGE_KEY}